[tools]
selene = { source = "Kampfkarren/selene", version = "0.25.0" }
rojo = { source = "rojo-rbx/rojo", version = "7.4.0-rc2" }
stylua = { source = "johnnymorganz/stylua", version = "0.17.1" }
foreman = { source = "UpliftGames/wally", version = "0.3.2" }